### ISSUE TITLE
export `getCreateTx`

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#417]
Can `getCreateTx` get exported from client b/c i need a way to make transactions dynamically without the typed api since i am not generating descriptors. 

Context: https://github.com/paritytech/substrate-connect/pull/2074/files#diff-b8a6045c9dc87c6479d7a15973b74671ef75892a404e9a681da35f95d469a31bR94

**Comment by josepot** [comment]
Most definitely not, because it's an implementation detail, it's not part of the public API and it will change quite a bit over time, given the fact that the current implementation (and API) was the fastest way that I found to re-use the code that I used to implement the tx-helper.

That being said, in the future we want to provide a proper library that facilitates the creation of transactions. In the meanwhile, there is nothing stopping you from either:

a) make your own implementation, while improving on the current one (we may benefit from that b/c as I mentioned before the current implementation is not ideal)
b) copying the parts that you need (it's not a lot of code that you will have to copy, I think)
c) using the old libraries
