### ISSUE TITLE
SignerPayloadJSON type mismatch

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-api/polkadot-api#449]
The `pub(extrinsic.sign)` payloads sent by PAPI to the wallet don't match the expected shape

Wallets expect this shape (HexString for most fields) : 
https://github.com/polkadot-js/api/blob/master/packages/types/src/types/extrinsic.ts#L32

Payload actually sent by PAPI : 
![image](https://github.com/polkadot-api/polkadot-api/assets/26880866/9dd0962a-1590-45ce-a0e8-0bfa8e7e668c)

As you can see nonce, specVersion and transactionVersion (maybe more) are numbers instead of HexString.

I suspect this is why Nova breaks (app just closes, can't get any log) each time the dapp sends a payload to the wallet for signature

**Comment by josepot** [comment]
Thanks a lot for reporting this @0xKheops !

I do remember that first we tried passing binary data as HexStrings and it didn't work. I'm super certain of that. However, it seems that the reason why it didn't work is because we were sending the binary data as SCALE encoded data (adhering to the on-chain definitions found in the metadata). Then, out of trial and error we noticed that sending the data like this did work with the PJS extension, with Talisman and with Subwallet, so we just left it like that. I wish there was a proper spec on this, TBH.

On that note, please know that we have been collaborating with Parity to define a better (and library agnostic) [PolkadotSigner interface](https://github.com/polkadot-api/polkadot-api/blob/main/packages/signers/polkadot-signer/src/types.ts) that shouldn't have any of these issues.

We will try changing all those fields to send HexString data, but it would be really, really helpful if you could explain to us what is the "canonical" way of encoding those values as binary given the fact that it's quite obvious that they are not being SCALE encoded.

Thanks a lot!

**Comment by 0xKheops** [comment]
Hey @josepot 

We actually had to make a fix to Talisman to support specVersion being sent as number in the payload, did that when i first tried PAPI.

https://github.com/TalismanSociety/talisman/pull/1399

It looks like numbers are meant to be encoded as base 16, so I assume `0x${value.toString(16)}` should work
