### ISSUE TITLE
Getting "Uknown operationId on ..." for operations that appear known

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#470]
Run local zombienet with `yarn zombienet`, and use `yarn start` to run the code. 
Logs from the logs provider also attached. 

```
cornholio-osx3:~/work/parity/papi-repro/>yarn start
yarn run v1.22.22
$ node -r ts-node/register index.ts
tx 0x3d028400d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d01ba3baa483e7d1bb1db6617c516212954942ea1f7afd136970fa7187f0da0114c5f581f603651536c32eed7ab71dc3e431a7a5058673b86b4d1e5b7c211b3b38900080004030053996a12b5b69734139259b54899ffbe5b9c6640d2428f96510c24e1fd22f8b1070010a5d4e8
balance increase
Uknown operationId on {
  event: 'operationStorageItems',
  operationId: '14',
  items: [
    {
      key: '0x26aa394eea5630e07c48ae0c9558cef702a5c1b19ab7a04f536c519aca4983ac',
      value: '0x4b000000'
    }
  ]
}
Uknown operationId on { event: 'operationStorageDone', operationId: '14' }
submitted
```

If you read the logs, `"operationId":"14"` gets a `started` event first
```
cat papi-debug-relay.log |grep -F '"14"'
1-2024-05-02T13:01:18.030Z-<<-{"jsonrpc":"2.0","result":{"result":"started","operationId":"14","discardedItems":0},"id":"1-20"}
1-2024-05-02T13:01:18.030Z-<<-{"jsonrpc":"2.0","method":"chainHead_unstable_followEvent","params":{"subscription":"SN858qdZdmDCoIFL","result":{"event":"operationStorageItems","operationId":"14","items":[{"key":"0x26aa394eea5630e07c48ae0c9558cef702a5c1b19ab7a04f536c519aca4983ac","value":"0x4b000000"}]}}}
1-2024-05-02T13:01:18.030Z-<<-{"jsonrpc":"2.0","method":"chainHead_unstable_followEvent","params":{"subscription":"SN858qdZdmDCoIFL","result":{"event":"operationStorageDone","operationId":"14"}}}
```

P.S. there's also a typo in the word "Unknown" :)

[papi-repro.tar.gz](https://github.com/polkadot-api/polkadot-api/files/15188698/papi-repro.tar.gz)
[papi-debug-relay.log](https://github.com/polkadot-api/polkadot-api/files/15188705/papi-debug-relay.log)

**Comment by josepot** [comment]
This is a truly fascinating edge case!

Ok, so long-story short: that warning is completely harmless, and everything should work perfectly fine.

This is what's happening there are 2 storage queries that get started simultaneously (`1-19` and `1-20`), these are their corresponding logs:

```
1-2024-05-02T13:01:18.026Z->>-{"jsonrpc":"2.0","id":"1-19","method":"chainHead_unstable_storage","params":["SN858qdZdmDCoIFL","0x8a898a6ed155ae66e19113432395734e49a5af8649f432579a38eb374b2ee725",[{"key":"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9bfa570c0b1827aca63d7288eaec5e88a53996a12b5b69734139259b54899ffbe5b9c6640d2428f96510c24e1fd22f8b1","type":"value"}],null]}
1-2024-05-02T13:01:18.026Z->>-{"jsonrpc":"2.0","id":"1-20","method":"chainHead_unstable_storage","params":["SN858qdZdmDCoIFL","0x8a898a6ed155ae66e19113432395734e49a5af8649f432579a38eb374b2ee725",[{"key":"0x26aa394eea5630e07c48ae0c9558cef702a5c1b19ab7a04f536c519aca4983ac","type":"value"}],null]}
```
What happens immediately after is that we get the response of the first storage query (before we receive the `started` response for the second one, BTW):

```
1-2024-05-02T13:01:18.026Z-<<-{"jsonrpc":"2.0","result":{"result":"started","operationId":"13","discardedItems":0},"id":"1-19"}
1-2024-05-02T13:01:18.026Z-<<-{"jsonrpc":"2.0","method":"chainHead_unstable_followEvent","params":{"subscription":"SN858qdZdmDCoIFL","result":{"event":"operationStorageItems","operationId":"13","items":[{"key":"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9bfa570c0b1827aca63d7288eaec5e88a53996a12b5b69734139259b54899ffbe5b9c6640d2428f96510c24e1fd22f8b1","value":"0x000000000000000001000000000000000010a5d4e80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080"}]}}}
1-2024-05-02T13:01:18.026Z-<<-{"jsonrpc":"2.0","method":"chainHead_unstable_followEvent","params":{"subscription":"SN858qdZdmDCoIFL","result":{"event":"operationStorageDone","operationId":"13"}}}
```

It turns out that there was a race between those 2 different storage calls, so this has now cancelled the first request. If we had already received the `started` event for the `1-20` storage request, then this would have triggered a [`chainHead_v1_stopOperation`](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_v1_stopOperation.html#chainhead_v1_stopoperation) request for canceling the operation. However, we haven't received a response yet for that request. Therefore, since it's considered cancelled we stop paying attention to its response, meaning that when its operation-id arrives we are no longer interested, so we don't store it, and thus when the other events come we log those pesky "Uknown operation id on" messages, which are completely harmless.

To be fair, I now realize that the proper way of canceling an operation for which we haven't received its `started` event should be improved. I.e we should wait until receiving the `started` response and in that same moment trigger the `stopOperation` request.

It's a super-low priority thing, because leaving aside those annoying messages everything works as it should, but we will tackle this, which is why I'm leaving this issue open.

Thanks for reporting this!

PS: next time please log somewhere the random address that was generated 🙏 I had to spend 10 minutes extracting it from the logs so that I could use the `logsProvider` to reproduce the issue 🙂
