### ISSUE TITLE
Add more RPC methods to client

### ISSUE THREAD

**Issue by timbrinded** [polkadot-api/polkadot-api#471]
Currently the PolkadotClient has a handful of RPC methods - but sadly there isn't the most elemental of them all.. `system.chain()` !! We have `chainSpec_v1_chainName` which is not ubitquitous amongst the rest of Polkadot chains

**Comment by timbrinded** [comment]
Do you mind if i raise a PR to add a load of common RPC methods to here:
https://github.com/polkadot-api/polkadot-api/blob/21165d7036a9832b146891be2a891968e4954492/packages/client/src/client.ts#L116

The greatest hits like:
- system_properties
- system_chain
- system_version
- state_getRuntimeVersion 
etc

**Comment by josepot** [comment]
It's a bit old now and things have improved quite a bit since it was written, but please [read this](https://forum.polkadot.network/t/new-json-rpc-api-mega-q-a/3048#why-do-we-need-a-new-json-rpc-api-9).

> The greatest hits like:
> 
> * system_properties

Can be accessed via `(await client.getChainSpecData()).properties`

> * system_chain

Can be accessed via `(await client.getChainSpecData()).name`

> * state_getRuntimeVersion

can be accessed via `typedApi.constants.System.Version()`

> * system_version

I will try to find out what the proper way to access it is using the new JSON-RPC API is.

> Do you mind if i raise a PR to add a load of common RPC methods to here:

Please don't. This library is not going to add any first-class support for the legacy JSON-RPC API, for the reasons outlined in [this forum post](https://forum.polkadot.network/t/new-json-rpc-api-mega-q-a/3048/1). Our goal should be to help deprecate the legacy JSON-RPC API. Therefore, if there is something that can't be done via the new JSON-RPC API, which can be done with the legacy one, then we should improve the new spec, so that it can be done in a properly documented manner.

**Comment by josepot** [comment]
After some digging, it turns out that `system_version` is the concatenation of the `spec_version` plus the commit at which point one particular node was compiled. Therefore, `system_version` belongs into the category of endpoints meant for debugging purposes, because it's not on-chain data.

The reason being that it's an API that assumes that you are communicating with one node in particular, when all the other APIs that we provide assume that the client is actually connected to many different peers at the same time.

However, once again, we will provide a way for consumers to have access to the underlying `request` that could be used for these kinds of situations.
