### ISSUE TITLE
`file:` protocol break `yarn install --immutable`

### ISSUE THREAD

**Issue by tien** [polkadot-api/polkadot-api#597]
Since Yarn's lockfile will use the entire content of the `file` dependency to compute its hash value, a clean installation from CI will result in a lockfile update, breaking `yarn install --immutable`.

**Comment by voliva** [comment]
Hey, thank you very much for raising and the possible fix.

I'd like to take a second look though, because the package version of the descriptors should remain stable if the metadata doesn't change. If we can avoid having to check for specific versions of package managers, that would be a plus.

**Comment by tien** [comment]
Yeah make sense. Though Yarn can be a pain if your aim is cross pkg manager behaviour parity 😅

Also fwiw, I personally believe targeting optimal protocol depending on the pm should be okay. Especially now that `package.json` is expected to specify the `packageManager` field.

**Comment by voliva** [comment]
After looking it more carefully I understood the problem was not the version the codegen generates, but rather the integrity check yarn runs on the package. I've checked this doesn't effect pnpm, bun or npm.

Unfortunately, the `packageManager` field is not well-standarazied yet. It's an experimental [corepack feature](https://nodejs.org/api/packages.html#packagemanager) that only supports yarn and pnpm. And from all the package managers I've tried, only yarn2+ populates it when creating a new project.

But that might be the only solution for this issue, and since yarn2+ supports it and it's the only one having it, I think it makes total sense 👍
