### ISSUE TITLE
Get block hash from block number

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#701]
Hey team, is there a way to get the block hash from a block number (equivalent of `api.rpc.getBlockHash(number)` with pjs)?

Context: I need to inspect some blocks that aren't the latest or the finalized, and all I have is their height. I'd then use `client.getBlockBody(hash)`.

Thanks

**Comment by josepot** [comment]
> I'd then use `client.getBlockBody(hash)`

You won't be able to do this. You can't request the body of a block that you have not "witnessed". For these kinds of things you should be using either an indexer or an archive-node. There is no guarantee that a full-node will be able to give you the body of an old block. AFAIK full-nodes store all the headers, but not all the block-bodies.

> is there a way to get the block hash from a block number (equivalent of `api.rpc.getBlockHash(number)` with pjs)?

Currently we only support the following groups of functions of the new [JSON-RPC spec](https://paritytech.github.io/json-rpc-interface-spec/): `chainHead`, `transaction` and `chainSpec`.

The functionality that you are looking for will be available on archive nodes under the [`archive_unstable_hashByHeight`](https://paritytech.github.io/json-rpc-interface-spec/api/archive_unstable_hashByHeight.html#archive_unstable_hashbyheight) method.

However, once again, depending on what it is that you are doing, then you probably would be better off using an indexer.

That being said, if you **really** know what you are doing, then you could use the `_request` method, which -as its docs state- is meant as a scape-hatch for some "odd" situations:

```
  /**
   * This API is meant as an "escape hatch" to allow access to debug endpoints
   * such as `system_version`, and other useful endpoints that are not spec
   * compliant.
   *
   * @example
   *
   *   const systemVersion = await client._request<string>("system_version", [])
   *   const myFancyThhing = await client._request<
   *     { value: string },
   *     [id: number]
   *   >("very_fancy", [1714])
   *
   */
```

So, perhaps you could use it for accessing the legacy RPC methods that you are looking for.

May I ask why you need this for?

If I had to make a wild guess, then my guess would be that you need this because you are trying to find out what the call-data is for one of the open multisig operations?

**Comment by Tbaut** [comment]
Thanks for the pointers. Yeah I'm using an archive node. And from my experience, full nodes actually don't prune the data for a very long time (like more than a couple months).

You guessed right, this is what Multix has been doing successfully, and without an indexer (for this, bc it still needs and indexer to know about pure proxies unfortunately), for almost 2 years. The first multisig call, with the call data is stored in a block. The storage of pending multisig transactions includes the origin block, the extrinsic height, and the hash. So all I need to know the callData and present it to users is to go fetch it, in past blocks. This is more reliable, and much more open than an indexer, since any UI can go and fetch it. With the previous way, what pjs/apps is still doing, an indexer wouldn't even be able to get the callData since it's generally not part of the call (they use `approve_as_multi`, although I use `as_multi`). The only downsides are the fee cost, but it is negligible, and the fact that the call data is disclosed before the call is executed.

**Comment by carlosala** [comment]
Hi! Just closing this since it does not require any action from our side.
From a block number you can do `api.query.System.BlockHash.getValue(<yourBlockNumber>)`.

**Comment by Tbaut** [comment]
oh wow even better, thank you so much

**Comment by carlosala** [comment]
Yeah, it's nice but only ~7h of blocks.

**Comment by carlosala** [comment]
In order to know the amount of blocks that will be saved you can check `api.consts.System.BlockHashCount`. In case of Polkadot at this point is 4096, but it might change at some point.
