### ISSUE TITLE
Dry run prevents a tx from being submitted based on wrong fee calculation

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#753]
Hello there, I've had a report from a user on Delegit where the tx fails on Delegit, but succeeds elsewhere. The error is displayed before being broadcasted, so I imagine that there's a dry run or and `apply_extrinsic` that's performed.

We print errors, and this one was:
```json
InvalidTxError: {
  "type": "Invalid",
  "value": {
    "type": "Payment"
  }
}
```

the Tx fee estimation is pretty wrong, and we're talking about big batches that accumulate any wrong calculation.
Here's an example https://polkadot.subscan.io/extrinsic/0x277400e64356d10b599612b95fed712c029b2a0fd4f7d9f72265c57b9769984d
estimation is 3x the reality.
![image](https://github.com/user-attachments/assets/e0140832-b016-4d91-af6b-e8089a1e03a0)

The tx from the user in question is even wilder, it's off by 5x https://polkadot.subscan.io/extrinsic/22738944-3
![image](https://github.com/user-attachments/assets/3fd839b3-2765-48ff-b1de-fa761832a00c)

**Comment by josepot** [comment]
Sorry, but I'm not following... The discrepancy between the estimated fee and the used fee is a problem with the weights of the transactions of this pallet... A possible solution could be to create transactions that are more granular, so that the estimated fee doesn't go bananas... However, that has nothing to do with our library. That is an issue with PolkadotSDK.

> I've had a report from a user on Delegit where the tx fails on Delegit, but succeeds elsewhere

I'm sorry, but this is a bit hard to believe. This transaction has been deemed as invalid, an invalid transaction can not succeed somewhere else. The transaction was certainly different. I would have to compare the 2 transactions to understand why.

The error that you received is because we must check the validity of the transaction before broadcasting it. We can not broadcast a transaction if is invalid. If it has succeeded elsewhere, then either the transaction was different, or something changed between blocks which made the transaction valid. In this case, what prevented the transaction from being broadcasted is not a dry-run, but the validity check.

The only way to make sense of this is to compare these 2 different transactions.

**Comment by Tbaut** [comment]
I don't have the 2 transactions unfortunately, since 1 failed the dry run and wasn't broadcasted, and the other was submitted with another tool (Nova). I also can't be absolutely sure of the report.

I know the issue is from the Polkadot SDK having crazy fee calculation, and I believe Nova doesn't do any dry run. So I could see a scenario where:
- I use Delegit / papi, I barely have enough funds to pay, dry run with wrong fees says it won't work so the tx is aborted
- I use something else, with pjs or in Nova case their own lib, no dry run YOLO, it works

I don't have a good suggestion, but I'm thinking if I was able to influence the dry run, for this case, I'd actually de-activate it, since it's super wrong. This would be at the cost of a very small fraction of users having their tx to actually fail, and paying the (super low) fees. The UX overall would be better, and no-one would question the app I built.

**Comment by josepot** [comment]
> I don't have the 2 transactions unfortunately, since 1 failed the dry run

It did not fail on the dry-run. It failed on the validation of the transaction. I know because of the error that you shared.

> and the other was submitted with another tool (Nova)

With the same signer? Because the reason why the transaction was deemed invalid is because the signer didn't have enough funds to pay for the fees.

> I believe Nova doesn't do any dry run

Again, this is not about the dry-run. This is the runtime saying that the transaction is invalid. If you try to create an invalid transaction with nova, then the transaction won't be broadcasted either. However, Nova probably has logic in place to ensure that a user can't create an invalid transaction.

> * I use Delegit / papi, I barely have enough funds to pay, dry run with wrong fees says it won't work so the tx is aborted
> * I use something else, with pjs or in Nova case their own lib, no dry run YOLO, it works
> 
> I don't have a good suggestion, but I'm thinking if I was able to influence the dry run, for this case, I'd actually de-activate it, since it's super wrong. This would be at the cost of a very small fraction of users having their tx to actually fail, and paying the (super low) fees. The UX overall would be better, and no-one would question the reliability of the app.

Sorry, but this is none-sense.

A node **can not** and should **not** spam/broadcast invalid transactions, and if they do, then they get banned/ignored by the rest of the network, because they are deemed as a bad actor.

The estimate fee is calculated by the runtime, not by PAPI. If the estimate fee says that the transaction can cost up to a certain amount and the balance of the signer is less than that amount, then the transaction will **always** be invalid.

The only way to know whether the transaction will end-up costing less is by actually having a node execute the transaction. Nodes should not and will not execute a transaction that has the potential of being economically unsound. That's why a transaction that has an estimate fee very high is deemed invalid. So, if you have a balance of 1.1 DOTs and the estimate fee of a tx that you want to broadcast is 1.11, then the transaction will be invalid (even if in reality the execution of that transaction would end up costing 0.1). No node will broadcast the transaction and/or put it in their tx-pool.

The reason being that if a transaction can potentially cost more than what the signer can pay, then the transaction is flagged as invalid, and the nodes will reject it. End of story. Because if nodes decided to spent resources executing transactions that have the potential of not being paid, then it would be trivial to orchestrate a denial of service attack and bring down the network.

Once again: this is not something that can be solved by having a library "skip a dry run".

The issue here is that after the transaction has been created, we have checked against the runtime of the chain and the runtime has said: "yo, this transaction is invalid because the signer can't pay for it, do not even attempt to broadcast it or you will regret it".

Even if you know that in reality the transaction will end up costing less, there is no way to prove that to the network. You can't broadcast a transaction saying: "hey, the runtime says that it's invalid because it thinks that it can cost a lot of resources, but please trust me, that's not the case". That is absurd.

If the runtime deems a transaction as invalid, then that transaction will not be broadcasted and if it has been broadcasted, then as soon as it becomes invalid it will be removed from the transaction pools.

It is possible, though, that a transaction is invalid in one block because the signer can't pay for it, but then in the next block the signer receives the funds that they were missing, and then the transaction would become valid and could be broadcasted.

------------------

Please, also consider the idea that it could be possible that delegit could have added redundant or unnecessary calls inside the batch, which would cause for the estimate of the transaction to cost a lot more.

**Comment by Tbaut** [comment]
> Again, this is not about the dry-run. This is the runtime saying that the transaction is invalid. If you try to create an invalid transaction with nova, then the transaction won't be broadcasted either. However, Nova probably has logic in place to ensure that a user can't create an invalid transaction.

Ok got it thanks for the explanation. The runtime does the check, and it's nothing to do with papi.

> Please, also consider the idea that it could be possible that delegit 
yeah totally I checked this. I managed to get the extrinsics made by Nova, and instead of 1 big batch, they let users sign 3 batch transactions. Which cuts down the estimation hallucination, although the UX is worse for users.

Anyways, it's indeed got nothing to do with papi, I erroneously thought that if the nodes were checking, the result would be the same as when there's a failed runtime execution, I thought we'd see the failed tx in an explorer.
