### ISSUE TITLE
`client.getChainSpecData` doesn't give the same SS58prefix as the constant `System.SS58prefix` on Paseo

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#767]
FWIW Paseo was 42, and is now 0 which is probably the reason, so this is expected. I guess this 42 is in the genesis, and it's been later changed in a runtime upgrage.

`client.getChainSpecData().then(({ properties}) => console.log(properties.ss58Format))`

It's not a bug per se.. and the name `getChainSpecData` is good to understand the issue. Now I expect devs to use this, like me, to get started and show the right decimal, token, prefix, and they may not know that Paseo changed, or that the current state isn't the same as what was in the genesis. Paseo is isolated today, but some other network in the future will change, as we expect them to all use 0 eventually on Polkadot for instance.

Let me know what's your suggestion. I'd consider using another function like `getChainProperties`, and use the latest runtime constants. In the mean time I'll ignore this property and use the system.Ss58Prefix.

**Comment by josepot** [comment]
The chainspec data is "trusted data", it's completely arbitrary data.

The `System.SS58prefix` **is** what matters, because it's what it's in the runtime of the chain. You can use a light-client and verify that value.

If you are getting discrepancies, that's probably because whoever setup the node messed up the chainspec properties.  Please reach out to them. This is not an issue with polkadot-api.

Also, I have explained over and over, in many occasions why the `getChainSpecData` should not be used by normal DApp developers. It's mostly for dev-tools and doing introspection. Do not ever create a DApp that relies on `getChainSpecData`.

**Comment by Tbaut** [comment]
Having a config file in every single app out there, that everyone will have to create/update is certainly not great. Having a list of rpc/relay for light client, and fetching everything upon connection sounds so much better. The decimals & tokens, should absolutely be on chain IMHO. Maybe this is something @kianenigma can help me with to write a Polkadot sdk issue, and get tht in the wishlist.

For now think this is something that we need to have in the docs, it it won't prevent every mistake, it's a start. If I found `getChainSpecData`, others will find it. and the mistake will be made again.

**Comment by josepot** [comment]
> For now, I think this is something that we need to have in the docs. It won't prevent every mistake, but it's a start. If I found `getChainSpecData`, others will find it, and the mistake will be made again.

We are planning significant improvements to the documentation, and I will ensure this issue is explained more thoroughly. I had assumed that DApp developers understood that the 'properties' entry in the chainspec is "trusted data" and shouldn't be relied upon. Since that might not be the case, I'll make sure we emphasize this point clearly in the updated docs.

----------------------

The issue of moving properties on-chain is a recurring topic. For instance, refer to [this conversation](https://github.com/polkadot-fellows/RFCs/pull/8#issuecomment-1641477245) that took place during the review of RFC-8.

**Wouldn't it be beneficial if we had a standard way to access this information trustlessly?**

Absolutely - it would be ideal.

**Do we currently have a standard that enables this?**

Unfortunately, we do not.

While we indirectly have a pseudo-standard for accessing the SS58-prefix through RFC-78, there are [teams within the "Polkadot UX Guild" advocating for ignoring the on-chain value of their own chains](https://forum.polkadot.network/t/unifying-polkadot-ecosystem-address-format/10042/13?u=josep) 🙃🤦.

**Is anyone likely to champion and enforce such a standard?**

It's highly unlikely. The ecosystem currently resembles a "wild west," where incentives are not aligned to promote standards—in fact, they often do the opposite. This isn't just my perspective; you might reach out to the Web3 Foundation, which hasn't yet [completed the Polkadot specification](https://github.com/w3f/polkadot-spec/issues), to ask why they're not actively championing these standards. Without a dedicated foundation to promote and enforce standards, we are screwed IMHO.

**So what can we do in the meantime?**

Given the current situation and the unlikelihood of having this information standardized on-chain soon, the best advice for dApp developers is to maintain their own configuration files for each network. Alternatively, setting up a centralized GitHub repository to store these configurations is a possibility. Personally, I find this solution less than ideal and somewhat unsettling, so I prefer not to partake in it.

For context, if RFC-8 were ever implemented, I'm fairly confident it would address this problem and establish a de facto standard, much like how FRAME has set standards in other areas.

**Is there any chance RFC-8 will be implemented?**

Who knows? Probably not, though. Despite being one of the first RFCs approved, to my knowledge, there have been zero efforts toward its implementation so far.

I had hoped my team could eventually tackle this issue. However, we're currently overwhelmed with work and would require extensive coordination with Parity to proceed. Unfortunately, this means it's unlikely to happen anytime soon.

**Comment by Tbaut** [comment]
> I'll make sure we emphasize this point clearly in the updated docs.

Thank you! I used to know what's a chain spec, and I forgot. I talked about "genesis" above which is totally different, and as you said: non-trusted, unlike the chain spec that contains the genesis. The amount of Dapp devs that know what a chain spec file is, is probably very very low since it's linked to nodes, that Dapp devs generally don't mess with.

I came across this yesterday as an example, it's a papi step by step tutorial by dotcodeschool.com that just got release. I'll ping Nikos to change this. Dapp devs should ideally not be told about this function at all.
![image](https://github.com/user-attachments/assets/abbae7fe-9202-44b5-8da2-65afd2687b50)

**Comment by wirednkod** [comment]
Thnx @Tbaut for the information.
I would prefer to add a note that I am using that for the sake of the tutorial and that normally in production developers should NOT rely on that due to the things that Josep mentioned.

I will update accordingly

@josepot if you think it should be removed or something specific to be added - please let me know 🙏🏽
