### ISSUE TITLE
Unable to use WebSocket provider with Remix SSR

### ISSUE THREAD

**Issue by tuul-wq** [polkadot-api/polkadot-api#790]
Faced a problem trying to use WebSocket provider (web & node) with [Remix](https://remix.run/docs/en/main).

Steps to reproduce:
- Create a basic Remix app using `npx create-remix@latest`
- Import provider function 
```js
import {getWsProvider} from "polkadot-api/ws-provider/web";
```
- Create `PolkadotClient` at default page
```js
const client = createClient(withPolkadotSdkCompat(getWsProvider('wss://westend-rpc.dwellir.com')));
```
- Run `npm run dev`

Web WS provider throws error:
```
4:16:19 PM [vite] Internal server error: WebSocket is not defined
      at file:///Users/yaroslav/Documents/Work/remix-papi/node_modules/@polkadot-api/ws-provider/dist/web/esm/web.mjs:4:45
      at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
      at async nodeImport (file:///Users/yaroslav/Documents/Work/remix-papi/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:53045:15)
      at async ssrImport (file:///Users/yaroslav/Documents/Work/remix-papi/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52903:16)
      at async eval (/Users/yaroslav/Documents/Work/remix-papi/app/routes/_index.tsx:6:31)
      at async instantiateModule (file:///Users/yaroslav/Documents/Work/remix-papi/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52961:5)
```

Error for node provider:
- Same steps but provider is for node
```js
import {getWsProvider} from "polkadot-api/ws-provider/node";
```
Node WS provider throws error:
<img width="768" alt="image" src="https://github.com/user-attachments/assets/64658313-64cc-481d-a497-63a40e30ce79">

**Comment by carlosala** [comment]
Hi! Thanks for the report! This is indeed an issue with SSR using the same code for server (nodeJS) and web bundles, and `WebSocket` not being implemented natively for NodeJS <22.
There are two solutions to this problem.

1. Use nodeJS 22, and import from the `web` export. It'll work out of the box. From that version on, NodeJS implements the `WebSocket` natively. [NodeJS 22 will become LTS in 2 weeks](https://github.com/nodejs/release?tab=readme-ov-file#release-schedule), so it wouldn't be that much of a problem.
2. If you want to use NodeJS 20 (or anCreate a `provider.ts` file with the following code. `vite` will take care of it and strip the unused branches, so no increase in bundles 👍🏻 

```typescript
import { getWsProvider as serverProvider } from "polkadot-api/ws-provider/node";
import { getWsProvider as clientProvider } from "polkadot-api/ws-provider/web";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const getWsProvider: typeof clientProvider = (...args: [any]) => {
  if (import.meta.env.SSR) return serverProvider(...args);
  else return clientProvider(...args);
};
```

And when creating the client, instead of importing `getWsProvider` from our export, just import it from that file.

Feel free to comment anything else and we will reopen, I think this should solve it!
