### ISSUE TITLE
RPC Error: `RpcError: Maximum number of chainHead_follow has been reached`

### ISSUE THREAD

**Issue by rossbulat** [polkadot-api/polkadot-api#842]
Carlo and I have been discussing this behaviour - I have noticed that I am getting this `chainHead.follow$` error on multiple RPC providers:

```
error:  RpcError: Maximum number of chainHead_follow has been reached
```

I am not sure why this is happening - it apears that the observables are calling unsubscribe successfully before resolving. I guess nodes have certain limitations on the amount of active connections but this never happened with PJS API.

I'm also getting the error when running my tests repo where there is only one follow$ subscription taking place.

Here is a getter for the chain spec, that just spins up an observable and resolves the function once the spec is received: https://github.com/polkadot-cloud/polkadot-staking-dashboard/blob/main/src/model/Observables/ChainSpec.ts

I have put unsubscribe literally everywhere the function resolves or rejects, I seem to be getting a successful chain spec result, but the error is still being fired.

**Comment by josepot** [comment]
The error you're seeing, `RpcError: Maximum number of chainHead_follow has been reached`, is a known limitation specified in the JSON-RPC spec. For details, please refer to these sections of the spec: [ref 1](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_v1_follow.html#multiple-subscriptions) and [ref 2](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_v1_follow.html#possible-errors).

This behavior differs from PJS API because PJS doesn’t use the new JSON-RPC spec.

Regarding the code you shared, it's important to keep in mind that the `@polkadot-api/observable-client` package is designed primarily as a low-level tool for very advanced users —not for direct use in DApps. The code snippet provided clearly utilizes the `observable-client` APIs in a way that wasn’t intended.

In general, we recommend using the documented top-level API, which leverages `observable-client` to efficiently multiplex `chainHead` subscriptions across different operations, manages cached streams, and handles unsubscription automatically. This approach should prevent the error you're encountering. Our documentation ([docs](https://papi.how/)), examples ([example 1](https://github.com/polkadot-api/react-teleport-example), [example 2](https://github.com/polkadot-api/web3-blockspace-actions)), and sample projects illustrate the proper usage of the top-level client library.

Think of `@polkadot-api/observable-client` as the equivalent of `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED`—it’s intended for internal or advanced use only. If there’s a specific reason preventing you from using the top-level API, please let us know! We’d love to understand your use case better and see if we can improve the library to support it.

**Comment by rossbulat** [comment]
The top level API is not viable for a general purpose Dapp that handles a large number of networks unfortunately, so have resorted to use the lower level API.

**Comment by josepot** [comment]
> The top level API is not viable for a general purpose Dapp that handles a large number of networks unfortunately

😅 what? why?

The PAPI top-level API is actually built to support a large number of networks efficiently. Please check out these resources, which demonstrate how PAPI handles multi-network DApps:

- [Video overview](https://www.youtube.com/watch?v=fj63gYJmuIk&t=741s)
- [React Teleport Example](https://github.com/polkadot-api/react-teleport-example)
- [Web3 Blockspace Actions Example](https://github.com/polkadot-api/web3-blockspace-actions)
- [Compatibility](https://papi.how/typed#getcompatibilitylevel) and [Codegen Whitelist](https://papi.how/codegen#whitelist)

If there’s a specific limitation you’re running into, please let us know—we’d love to understand and address any gaps.

**Comment by rossbulat** [comment]
Well this is not the advice we have been given when we asked for implementation guidance. I have no choice but to roll back support until a concise answer is provided as to the direction the dapp should be headed in...

**Comment by josepot** [comment]
> Well this is not the advice we have been given when we asked for implementation guidance.

It seems there might be some confusion regarding the guidance you've received.

When @carlosala provided implementation advice, it was focused on using the low-level libraries for creating development tools. This guidance is tailored for advanced use cases and may not be optimal for building general-purpose DApps.

For DApp development, we recommend using the top-level API, which has been optimized to handle a large number of networks efficiently. The advice for building development tools doesn't directly apply to crafting DApps, and using the top-level API should help avoid the issues you're encountering.

We've intentionally designed the main library to abstract away the complexities of the low-level APIs, making it easier for DApp developers to build and maintain their projects. The low-level APIs are still available for those who need them but are not exposed through the main library to simplify the development process.

We have detailed explanations and support available through GitHub issues and our Polkadot-api Early Adopters Matrix group. We'd be happy to continue the conversation via these channels to provide more specific guidance and address any other questions you might have.

Please let us know if there's anything we can do to help you.
