### ISSUE TITLE
How do query for ss58 pubkeys?

### ISSUE THREAD

**Issue by flipchan** [polkadot-api/polkadot-api#873]
Hello,
 

The documentation tells you how to get the balance with the system pallets and the account call.
But this is only for ss58 addresses, why doesnt it work with pubkeys?

```ts
 const account_pubkkey = '0x7279fcf9694718e1234d102825dccaf332f0ea36edf1ca7c0358c4b68260d24b';
 const api = client.getTypedApi(custompolkadot)
 console.log(`got api!`)
 const query = await api.query.System.Account.getValue(
 "16JGzEsi8gcySKjpmxHVrkLTHdFHodRepEz8n244gNZpr9J" // oinly works with encoded addresses not pub key
 )
```

How do you query for the pubkey? do you have to manually convert it or can an auto converter be added to papi for this?

**Comment by josepot** [comment]
The types clearly indicate that the expected input is an `SS58String`:
![image](https://github.com/user-attachments/assets/8b57ef6a-d5da-441e-aed3-13bc037d9441)

That is because in Polkadot addresses are formatted like that for a number of reasons. Generally speaking, no one uses the hexadecimal public key for sharing their addresses, because the ss58 format includes the checksum so it has some advantages over the public key.

That being said, it's trivial to convert a public key to an `SS58String`.

> How do you query for the pubkey?

```ts
import { AccountId } from "polkadot-api"

const publicKey = "0x7279fcf9694718e1234d102825dccaf332f0ea36edf1ca7c0358c4b68260d24b"
const address = AccountId().dec(publicKey)
const query = await api.query.System.Account.getValue(address)
```
